config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  resources :posts do
    resources :likes
    resource :charge
    resource :map
  end
  
  resources :tags

  root to: 'posts#index'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
  has_many :likes
  has_and_belongs_to_many :tags
  
  has_attached_file :picture, 
  styles: { medium: "350x350#"},
  :storage => :s3,
  :s3_credentials => {
    :bucket => 'insta300px',
    :access_key_id => Rails.application.secrets.s3_access_key_id,
    :secret_access_key => Rails.application.secrets.s3_secret_access_key
  }

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  validates :user_id, presence: true
  validates :title, presence: {message: "You must add a title"}
  validates :price, presence: true, numericality: true

	def tag_list
	end

	def tag_list=(some_tags)
		return if some_tags.empty?

		some_tags.split(", ").uniq.each do |tag|  	
			self.tags << Tag.find_or_create_by(text: tag)
		end
	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts

	def to_param
		text.delete('#')
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :setup_new_post

  def setup_new_post
    @new_post = Post.new
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def index
  end

  def new
  end

  def show
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => (@post.price * 100).floor, # Amount must be in pence
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charges_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post.likes.create

    render json: { new_like_count: @post.likes.count }
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def show
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index]

	def index
		@posts = Post.all	
    @posts = Post.order(created_at: :desc)
    @posts
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post].permit(:title, :picture, :tag_list, :address, :price))
    @post.user = current_user
		if @post.save
      post_data = { 
        post_id: @post.id, 
        title: @post.title, 
        charge_url: "/posts/#{@post.id}/charge", 
        picture_url: @post.picture.url(:medium), 
        user_email: @post.user.email, 
        address: @post.address, 
        map_url: "/posts/#{@post.id}/map", 
        tag_list: @post.tags.map { |tag| {text: tag.text, url: "/tags/#{tag.text.delete('#')}"} }, 
        like_count: @post.likes.count 
      }
      Pusher['theinstagramapp_channel'].trigger('new_upload', post_data)
    end
      redirect_to '/'
	end

  def show
    @post = Post.find(params[:id])
    render "show.html.erb"
    # respond_to do |format|
    #   format.html
    #   format.json { render partial: 'post', locals: { post: @post } }
    # end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by!(text: '#' + params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  def show
    @posts = Post.where(user_id: params[:id])
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$<%= sprintf "%.2f", @post.price %></strong>!</h2>

app/views/charges/show.html.erb
<div class="container">
  <article class='post col-lg-10 col-md-offset-1'>
    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= @post.title %></h3>

        <% if @post.picture.present? %>
        <%= image_tag @post.picture.url, class: 'uploaded-pic' %>
        <% end %><br>
      </div>
    </div>
  </article>
</div>

<h1>Want to purchase this print?</h1>

<div class="payment-container">
  <%= form_tag post_charge_path(@post) do %>
    <article>
      <label class="amount">
        <h4>Amount: $<%= sprintf "%.2f", @post.price %></h4>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
            data-description="Payment for photo"
            data-amount="<%= (@post.price * 100).floor %>"></script>
  <% end %>
</div>

*Payments has been disabled at this time. Please check again later.

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="/"> Insta3∞px <span class="glyphicon glyphicon-heart-empty"></span></span> </a>
    </div>
    <div class="navbar-collapse collapse">
      <% if current_user %>
        <%= form_for(session, as: :user, url: destroy_user_session_path, method: :delete, html: { class: 'navbar-form navbar-right' } ) do |f| %>
          <div class="form-group"> Logged in as <%= current_user.email %></div>
          <!-- New Post Model trigger -->
          <%= link_to '#', :class => "btn btn-success navbar-btn", :'data-toggle' => "modal", :'data-target' => "#newPostModal" do %>
              <span>New Post</span>
              <span class="glyphicon glyphicon-edit"></span> 
          <% end%>

            <%= f.submit "Sign out", class: "btn btn-danger" %>
        <% end %>
      <% else %>
        <%= form_for(User.new, as: :user, url: new_user_session_path, html: { class: 'navbar-form navbar-right' } ) do |f| %>
          <div class="form-group">
            <%= f.email_field :email, autofocus: true, placeholder: "Email", class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
          </div>

          <%= f.submit "Sign in", class: "btn btn-success" %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_new_post_modal.html.erb
<div class="modal fade" id="newPostModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">New Post</h4>
          </div>
          <%= form_for @new_post, html: { multipart: true } do |f| %>
            <div class="modal-body">
                <%= f.label :title, 'Title*' %><br />
                <%= f.text_field :title %> <br />
                
                <%= f.label :tag_list, 'Tags' %> <br />
                <%= f.text_field :tag_list %> <br />
                
                <%= f.label :address, 'Location' %> <br />
                <%= f.text_field :address %> <br />
                
                <%= f.label :picture, 'Picture*' %><br />
                <%= f.file_field :picture %><br />

                <%= f.label :price, 'Price*' %><br />
                $<%= f.text_field :price, value: '0.00' %><br />
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-success">Post <span class="glyphicon glyphicon-edit"></span></button>
            </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="//d36xtkk24g8jdx.cloudfront.net/bluebar/c38fc5b/images/ico/favicon.ico">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    
    <title>Insta3∞px</title>
  </head>
    <%= render partial: 'layouts/navigation' %><!--/.navbar-collapse -->
  <main class="container">
    
    <%= yield %>

  </main>

  <section class="container">
    <hr>
    <footer>
      <p>Insta3∞px is made by <a href="http://www.github.com/thejennywang">Jenny Wang</a>, at <a href="http://www.makersacademy.com">Makers Academy</a>. &copy; 2014</p> 
    </footer>
  </section>
    <!-- New Post Modal -->
    <%= render partial: 'layouts/new_post_modal' %>
    <%= render partial: 'layouts/post_template' %>
    
    <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.bootstrapvalidator/0.5.1/css/bootstrapValidator.min.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.bootstrapvalidator/0.5.1/js/bootstrapValidator.min.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/maps/show.html.erb
<h2><%= @post.address %></h2>

<div id="map" data-id="<%= @post.id %>">
</div>

app/views/posts/_post.html.erb
<article class='post col-sm-6 col-md-4'>
  <div class="panel panel-default">
    <div class="panel-body">
      <h3><%= post.title %></h3>

      <% if post.picture.present? %>
        <%= link_to post_charge_path(post) do %>
          <%= image_tag post.picture.url(:medium), class: 'uploaded-pic' %>
        <% end %><br>
      <% end %>

      <small class="text-muted"><em>Uploaded by <%= post.user.email %></em></small><br />

      <% unless post.address.blank? %>
        Taken: <%= link_to post.address , post_map_path(post) %> <br>
      <% end %>

      <% unless post.tags.blank? %>
        Tags: <% post.tags.each do |tag| %>
        <%= link_to tag.text, tag %>
        <% end %>
      <% end %>

      <%= link_to post_likes_path(post), class: 'like-link' do %>
        <div class="like-btn btn btn-default btn-xs">
          <span class="glyphicon glyphicon-heart"></span> 
          <span class="like_count"><%= post.likes.count %></span>
        </div>
      <% end %>
      
    </div>
  </div>
</article>

app/views/posts/index.html.erb
<% if @posts.any? %>
<section class="row">
	<%= render @posts %>
</section>

<% else %>
	No posts yet
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <article class='post col-lg-10 col-md-offset-1'>
    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= @post.title %></h3>

        <% if @post.picture.present? %>
        <%= image_tag @post.picture.url, class: 'uploaded-pic' %>
        <% end %><br>
      </div>
    </div>
  </article>
</div>

<h1>Want to purchase this print?</h1>

<div class="payment-container">
  <%= form_tag post_charge_path(@post) do %>
    <article>
      <label class="amount">
        <h4>Amount: $<%= sprintf "%.2f", @post.price %></h4>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
            data-description="Payment for photo"
            data-amount="<%= (@post.price * 100).floor %>"></script>
  <% end %>
</div>

*Payments has been disabled at this time. Please check again later.

app/views/tags/show.html.erb
<h1><%= @tag.text%></h1>

	<%= render @tag.posts %>